TIp_Hub_Net/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('account/', include("account.urls")),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('register/login/', views.Register_Login_View.as_view(), name="register_login"),
    path('otpcode/', views.CzechOtpView.as_view(), name="check_otp"),
    path('panel/', views.PanelUser.as_view(), name="panel_user"),
    path('panelcreate/', views.PanelCreateUser.as_view(), name="panel_create"),
    path('panelupdate/<int:pk>', views.PanelUpdateUser.as_view(), name="panel_update"),
    path('profile/user/<int:pk>', views.ProfileUser.as_view(), name="profile"),
    path('author/about/<int:pk>', views.author_about.as_view(), name="author"),
    path('notification/', views.NotificationView.as_view(), name="notifications"),
    path('notification/update/<int:pk>', views.NotificationUpdate.as_view(), name="notifications_update"),
    path('notification/create/<int:pk>', views.NotificationCreate.as_view(), name="notifications_create"),
    path('logout/', views.user_logout, name='logout'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path('<int:pk>/<slug:slug>/', views.VideoDetail, name='detail'),
    path('<int:pk>/<slug:slug>/', views.HitCount.as_view(), name='detail'),
    path('videolist/', views.VideoList, name='video_all'),
    path('category/<int:pk>/', views.Category_Detail, name='category'),
    path('search/', views.Search, name='search'),
    path('like/<int:pk>/<int:id>/', views.likeDetail, name='like'),
    path('notification/<int:pk>', views.NotificationView.as_view(), name='notification'),
]

home/models.py
from django.db import models

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, View
from django.core.paginator import Paginator
from videos.models import Video, Comment, Like, Notification, Category
from hitcount.views import HitCountDetailView
from django.contrib import messages


# Home
class Home(ListView):
    model = Video
    ordering = ['-user', ]
    paginate_by = 6
    template_name = "home/home.html"


# list video and paginate
def VideoList(request):
    videos = Video.objects.all()
    page_number = request.GET.get("page")
    paginate = Paginator(videos, 6)
    object = paginate.get_page(page_number)
    context = {'object_list': object}
    return render(request, "home/video-list.html", context)

# category
def Category_Detail(request, pk=None):
    category = get_object_or_404(Category, id=pk)
    object = category.categorise.all().filter(status=True)
    context = {'object_list': object}
    return render(request, 'home/video-list.html', context)


# system like and view and comment
def VideoDetail(request, pk, slug):
    video = get_object_or_404(Video, id=pk, slug=slug)

    if request.method == "POST":
        parent_id = request.POST.get("parent_id")
        body = request.POST.get('body')
        Comment.objects.create(body=body, video=video, user=request.user, parent=parent_id)

    context = {'video': video}

    if request.user.is_authenticated:
        if request.user.likes.filter(video_id=pk, user_id=request.user.id).exists():
            context['is_liked'] = True
        else:
            context['is_liked'] = False

    return render(request, 'home/video-detail.html', context)


# system like
def likeDetail(request, id, pk):
    if request.user.is_authenticated:
        try:
            like = Like.objects.get(video__id=id, user_id=request.user.id)
            like.delete()
        except:
            Like.objects.create(video_id=pk, user_id=request.user.id)
        return redirect('home:video_all')
    return redirect("account:register_login")


# view count
class HitCount(HitCountDetailView):
    model = Video
    template_name = 'home/video-detail.html'
    context_object_name = 'video'
    slug_field = 'slug'
    count_hit = True


# search
def Search(request):
    q = request.GET.get("q")
    videos = Video.objects.filter(slug__icontains=q)
    page_number = request.GET.get("page")
    paginate = Paginator(videos, 2)
    object = paginate.get_page(page_number)
    context = {'object_list': object}
    return render(request, "home/video-list.html", context)


# Notification users
class NotificationView(View):
    def get(self, pk):
        notification = Notification.objects.get(id=pk)
        urls = notification.active.get_absulot_url()
        notification.delete()
        return redirect(urls)

home/templates/home/home.html
{% extends "base.html" %}
{% load static %}
{% load hitcount_tags %}
{% block title %} مجله {% endblock %}
{% block content %}
<main>
    <section class="py-5">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between mb-3">
                <h2 class="title-section">تازه ترین ویدیوها </h2>
                <a href="{% url "home:video_all" %}" class="btn custom-btn">
                    نمایش همه
                </a>
            </div>
            <div class="row">
                {% for video in object_list %}
                {% if video.status %}
                <!-- item -->
                <div class="col-md-6 col-lg-4 my-2">
                    <div class="custom-bg">
                        <div class="video-card">
                            <a href="{% url 'home:detail' video.id video.slug %}" class="position-relative d-block ">
                                <img src="{{ video.image.url }}" alt="" class="img-fluid w-100 h-100">
                                <div class="video-play-btn">
                                    <i class="fa fa-play"></i>
                                </div>
                                <div class="d-flex align-items-center justify-content-between video-category-time">
                                    <h6>{{ video.category.first }}</h6>
                                    <span class="vid-time">{{ video.time }}</span>
                                </div>
                                <div class="video-card-details">
                                    <div>
                                        <span>{% get_hit_count for video %}</span>
                                        <i class="fa fa-eye"></i>
                                    </div>
                                    <div>
                                        <span>{{ video.likes.all.count }}</span>
                                        <i class="fa fa-heart"></i>
                                    </div>
                                    <div>
                                        <span>{{ video.comments.all.count }}</span>
                                        <i class="fa fa-comment"></i>
                                    </div>
                                </div>
                                <div class="article-overlay"></div>
                            </a>

                        </div>
                        <a href="#">
                            <h5 class="video-card-title m-2">{{ video.body|striptags|truncatewords:"25" }}</h5>
                        </a>
                        <div class="my-3 pb-3 mx-2">
                            <i class="fa fa-user  ml-1 "></i>
                            <span>{{ video.user.username }}</span>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- end item -->
                {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock %}

home/templates/home/video-detail.html
{% extends "base.html" %}
{% load static %}
{% load hitcount_tags %}
{% block title %}{{ video.title }}{% endblock %}
{% block content %}
    <main>
        <section class="py-5">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <div>
                            <!-- video -->
                            <div class="video-player-box">
                                <div class="video-icon">
                                    <div class="btn video-btn" onclick="playvideo()" id="videobtn">
                                        <img src="{% static "image/play-video-btn.png" %}" alt="">
                                    </div>
                                </div>
                                <div class="video">
                                    <video width="100%" id="myVideo">
                                        <source src="{{ video.video.url }}" type="video/mp4">
                                    </video>

                                    <img src="{{ video.image.url }}" width="100%" height="100%"
                                         class="position-absolute video-poster" alt="">

                                    <div class="video-overlay"></div>
                                    <div class="video-description px-2 text-white">

                                        <p>{{ video.time }}</p>
                                    </div>
                                    <h5 class="close-btn" onclick="stopPlayer()">X</h5>
                                </div>
                            </div>
                            <!-- end video -->
                            <!-- title -->
                            <h3 class="video-title my-3"> {{ video.body|safe }}
                            </h3>
                            <div class="d-flex align-items-center justify-content-between border-bottom pb-3">
                                <p class="color78">{{ video.get_jalali_data }}</p>
                                <div class="d-flex align-items-center view-like">
                                    <div class="mx-3">
                                        <span>{% get_hit_count for video %}</span>
                                        <i class="fa fa-eye"></i>
                                    </div>
                                    <div>
                                        {% if is_liked %}
                                            <a href="{% url 'home:like' video.id video.pk %}"><i id="like"
                                                                                                 class="fa fa-heart"
                                                                                                 type='button'
                                                                                                 aria-hidden="true"></i></a>
                                        {% else %}
                                            <a href="{% url 'home:like' video.id video.pk %}"><i id="like"
                                                                                                 class="fa fa-heart-o"
                                                                                                 type='button'
                                                                                                 aria-hidden="true"></i></a>
                                        {% endif %}
                                    </div>
                                </div>

                            </div>
                            <!-- description -->
                            <div class="border-bottom pb-3">
                                <h4 class="my-3">درباره فیلم</h4>
                                <p class="color78">{{ video.about_video|safe }}</p>
                            </div>
                            <!-- end des -->

                            <!-- comments -->
                            {% if request.user.is_authenticated %}
                                <div>
                                    <div class="py-3">
                                        <span>{{ video.comments.all.count }}</span>
                                        <span>نظر</span>
                                    </div>

                                    <form action="#" id="comment" method="post">{% csrf_token %}
                                        <input type="hidden" name="parent" id="parent_id" value="">
                                        <textarea class="w-100 p-2 comment-area" name="body" id="body" cols="30"
                                                  rows="10"
                                                  placeholder="دیدگاه خود را بنویسید"></textarea>
                                        <div class="d-flex align-items-center justify-content-end pt-3">
                                            <button class="btn custom-btn">ارسال نظر</button>
                                        </div>
                                    </form>
                                    <!-- end comment -->
                                    {% for commit in video.comments.all %}
                                        {% if commit.parent == None %}
                                            <div class="comment my-3 p-2">
                                                <div class=" d-flex align-items-center justify-content-between">
                                                    {% if request.user.image %}
                                                        <div class="d-flex align-items-center justify-content-center">
                                                            <img src="{{ request.user.image.url }}" alt="student"
                                                                 class="user-profile">
                                                            <p class="user-name pr-2">{{ commit.user.username }}</p>
                                                        </div>
                                                    {% else %}
                                                        <div class="d-flex align-items-center justify-content-center">
                                                            <img src="{% static "image/sutdent-prof.png" %}"
                                                                 alt="student"
                                                                 class="user-profile">
                                                            <p class="user-name pr-2">{{ commit.user.username }}</p>
                                                        </div>
                                                    {% endif %}

                                                    <p class="comment-date-time">{{ commit.get_jalali_comment }}</p>
                                                </div>
                                                <p class="px-4 py-2 comment-text text-justify">{{ commit.body }}</p>
                                                {#                                                <div class="d-flex align-items-center justify-content-end reply"#}
                                                {#                                                     type='button'>#}
                                                {#                                                    <i class="fa fa-reply"></i>#}
                                                {#                                                    <button class="btn btn-info" onclick="set_value('{{ commit.id }}')">#}
                                                {#                                                        پاسخ به نظر#}
                                                {#                                                    </button>#}
                                                {#                                                </div>#}
                                            </div>
                                            {% for reply in video.comments.parents.all %}
                                                <div class="comment my-3 p-2 comment-child">
                                                    <div class=" d-flex align-items-center justify-content-between">
                                                        <div class="d-flex align-items-center justify-content-center">
                                                            <img src="{% static "image/sutdent-prof.png" %}"
                                                                 alt="student" class="user-profile">
                                                            <p class="user-name pr-2">{{ reply.user.username }}</p>
                                                        </div>

                                                        <p class="comment-date-time">{{ reply.get_jalali_comment }}</p>
                                                    </div>
                                                    <p class="px-4 py-2 comment-text text-justify">{{ reply.body }}</p>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            {% else %}
                                <div class="alert alert-danger">
                                    <a href="{% url "account:register_login" %}" class="alert-link">برای ثبت نظر وارد
                                        سایت شوید.</a>
                                </div>
                            {% endif %}
                            <!-- end comments -->
                        </div>
                    </div>
                    <!-- main -->
                    <!-- side -->
                    <aside class="col-md-4 ">
                        <div class="custom-bg p-2 teacher-card">
                            <div class="border-bottom py-3 text-center">
                                <h4>درباره مدرس</h4>
                            </div>
                            {% if request.user.image %}
                                <div class="d-flex align-items-center py-3">
                                    <img src="{{ request.user.image.url }}" alt="student" class="teacher-profile">
                                    <p class="user-name pr-2">{{ video.user.author }}</p>
                                </div>
                            {% else %}
                                <div class="d-flex align-items-center py-3">
                                    <img src="{% static "image/sutdent-prof.png" %}" alt="student"
                                         class="teacher-profile">
                                    <p class="user-name pr-2">{{ video.user.author }}</p>
                                </div>
                            {% endif %}
                            <p class="color78 teacher-description py-3">{{ video.user.about_user }}</p>

                            <div class="teacher-social-media d-flex align-items-center justify-content-center flex-wrap">
                                <a href=""> <i class="fa fa-instagram"></i></a>
                                <a href=""> <i class="fa fa-github"></i></a>
                                <a href=""> <i class="fa fa-linkedin"></i></a>
                                <a href=""> <i class="fa fa-twitter"></i></a>
                            </div>
                        </div>
                    </aside>
                    <!-- end side -->
                </div>
            </div>
        </section>
    </main>
    <script>
        function like(id, pk) {
            let element = document.getElementById("like")
            let count = document.getElementById("count")
            $.get(`/like/${id}/${pk}`).then(response => {
                if (response['response'] === "liked") {
                    element.className = 'fa fa-heart'
                    count.innerText = Number(count.innerText) + 1
                } else {
                    element.className = "fa fa-heart-o"
                    count.innerText = Number(count.innerText) - 1
                }
            })
        }

        // comment form
        function set_value(id) {
            document.getElementById('parent_id').value = id;
            window.location.href = "#body";
        }

        // video-player
        const videobtn = document.querySelector('.video-btn');
        const video = document.querySelector('.video');
        const videotag = document.querySelector('video')
        const videoDescription = document.querySelector('.video-description')
        const closeBtn = document.querySelector('.close-btn')
        const videoPoster = document.querySelector('.video-poster')
        const videoOverlay = document.querySelector('.video-overlay')

        function stopPlayer() {
            videobtn.style.display = "block";
            closeBtn.style.display = 'none';
            videoPoster.style.display = 'inline'
            video.style.zIndex = '-1'
            videotag.pause()
            videotag.style.borderRadius = '20px'
            videoDescription.style.display = 'flex'
            videotag.controls = false
            videotag.style.borderRadius = '15px'
            videoOverlay.style.display = 'block'
        }

        function playvideo() {
            videobtn.style.display = "none";
            video.style.zIndex = '22222'
            videotag.autoplay = true
            videotag.play()
            videotag.style.borderRadius = '20px'
            videotag.controls = true
            videoDescription.style.display = 'none'
            closeBtn.style.display = 'block'
            videoPoster.style.display = 'none'
            videoOverlay.style.display = 'none'
        }
    </script>
{% endblock %}

home/templates/home/video-list.html
{% extends "base.html" %}
{% load static %}
{% load hitcount_tags %}
{% block title %}لیست تمامی ویدیو ها{% endblock %}
{% block content %}
<main>
    <section class="py-5">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between mb-3">
                <h2 class="title-section">همه ویدیوها</h2>
            </div>
            <!-- all_video object-list -->
            <div class="row">
                {% for video in object_list %}
                {% if video.status %}
                <!-- item -->
                <div class="col-md-6 col-lg-4 my-2">
                    <div class="custom-bg">
                        <div class="video-card">
                            <a href="{% url 'home:detail' video.id video.slug %}" class="position-relative d-block ">
                                <img src="{{ video.image.url }}" alt="" class="img-fluid w-100 h-100">
                                <div class="video-play-btn">
                                    <i class="fa fa-play"></i>
                                </div>
                                <div class="d-flex align-items-center justify-content-between video-category-time">
                                    <h6>{{ video.category.first }}</h6>
                                    <span class="vid-time">{{ video.time }}</span>
                                </div>
                                <div class="video-card-details">
                                    <div>
                                        <span>{% get_hit_count for video %}</span>
                                        <i class="fa fa-eye"></i>
                                    </div>
                                    <div>
                                        <span>{{ video.likes.all.count }}</span>
                                        <i class="fa fa-heart"></i>
                                    </div>
                                    <div>
                                        <span>{{ video.comments.all.count }}</span>
                                        <i class="fa fa-comment"></i>
                                    </div>
                                </div>
                                <div class="article-overlay"></div>
                            </a>

                        </div>
                        <a href="#">
                            <h5 class="video-card-title m-2">{{ video.body|striptags|truncatewords:"25" }}</h5>
                        </a>
                        <div class="my-3 pb-3 mx-2">
                            <i class="fa fa-user  ml-1 "></i>
                            <span>{{ video.user.username }}</span>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- end item -->
                {% endfor %}
            </div>
            <!-- pageintor -->
            <!-- page_obj -->
            <div class="d-flex align-items-center justify-content-center mb-3 pagination">
                {% if object_list.has_other_pages %}

                {% if object_list.has_next %}
                <a href="?page={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="mx-1"><i class="fa fa-chevron-right"></i></a>
                {% endif %}

                {% for item in object_list.paginator.page_range %}
                {% if object_list.number == item %}
                <a href="?page={{ item }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="active mx-1">{{ item }}</a>
                {% else %}
                <a href="?page={{ item }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="mx-1">{{ item }}</a>
                {% endif %}
                {% endfor %}

                {% if object_list.has_previous %}
                <a href="?page={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="mx-1"><i class="fa fa-chevron-left"></i></a>
                {% endif %}

                {% endif %}
            </div>
        </div>
    </section>
</main>
{% endblock %}