TIp_Hub_Net/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('account/', include("account.urls")),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('register/login/', views.Register_Login_View.as_view(), name="register_login"),
    path('otpcode/', views.CzechOtpView.as_view(), name="check_otp"),
    path('panel/', views.PanelUser.as_view(), name="panel_user"),
    path('panelcreate/', views.PanelCreateUser.as_view(), name="panel_create"),
    path('panelupdate/<int:pk>', views.PanelUpdateUser.as_view(), name="panel_update"),
    path('profile/user/<int:pk>', views.ProfileUser.as_view(), name="profile"),
    path('author/about/<int:pk>', views.author_about.as_view(), name="author"),
    path('notification/', views.NotificationView.as_view(), name="notifications"),
    path('notification/update/<int:pk>', views.NotificationUpdate.as_view(), name="notifications_update"),
    path('notification/create/<int:pk>', views.NotificationCreate.as_view(), name="notifications_create"),
    path('logout/', views.user_logout, name='logout'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path('<int:pk>/<slug:slug>/', views.VideoDetail, name='detail'),
    path('<int:pk>/<slug:slug>/', views.HitCount.as_view(), name='detail'),
    path('videolist/', views.VideoList, name='video_all'),
    path('category/<int:pk>/', views.Category_Detail, name='category'),
    path('search/', views.Search, name='search'),
    path('like/<int:pk>/<int:id>/', views.likeDetail, name='like'),
    path('notification/<int:pk>', views.NotificationView.as_view(), name='notification'),
]

templates/panels/footer.html
{% load static %}
<script src="{% static "adminlte/plugins/jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "adminlte/plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{% static "adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "adminlte/plugins/chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "adminlte/plugins/sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "adminlte/plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "adminlte/plugins/jqvmap/maps/jquery.vmap.world.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "adminlte/plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "adminlte/plugins/moment/moment.min.js" %}"></script>
<script src="{% static "adminlte/plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "adminlte/plugins/summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "adminlte/dist/js/adminlte.js" %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static "adminlte/dist/js/pages/dashboard.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "adminlte/dist/js/demo.js" %}"></script>
</body>
</html>

templates/panels/header.html
{% load static %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{% block title %}پنل کاربر{% endblock %}</title>
<!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static "adminlte/plugins/fontawesome-free/css/all.min.css" %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet"
      href="{% static "adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
<!-- iCheck -->
<link rel="stylesheet" href="{% static "adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
<!-- JQVMap -->
<link rel="stylesheet" href="{% static "adminlte/plugins/jqvmap/jqvmap.min.css" %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static "adminlte/dist/css/adminlte.min.css" %}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{% static "adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static "adminlte/plugins/daterangepicker/daterangepicker.css" %}">
<!-- summernote -->
<link rel="stylesheet" href="{% static "adminlte/plugins/summernote/summernote-bs4.css" %}">
<!-- Bootstrap 4 RTL -->
<link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
<!-- Custom style for RTL -->
<link rel="stylesheet" href="{% static "adminlte/dist/css/custom.css" %}">
<link rel="stylesheet" href="{% static "css/font-vazir.css" %}">

templates/panels/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'home:home' %}" class="brand-link">
        <img src="{% static "image/logo2.png" %}"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">{% block main %}آموزش برنامه نویسی{% endblock %}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            {% if request.user.image %}
                <div class="image">
                    <img src="{{ request.user.image.url }}" class="img-circle elevation-2" alt="User Image">
                </div>
            {% else %}
                <img src="{% static 'image/sutdent-prof.png' %}" alt="image">
            {% endif %}
            <div class="info">
                <a href="#" class="d-block">{{ request.user }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            مقالات
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url "account:panel_user" %}"
                               class="nav-link {% if request.resolver_match.url_name == "panel_user" %}active{% endif %}">
                                <i class="fa fa-list nav-icon"></i>
                                <p>لیست ویدیو ها</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url "account:panel_create" %}"
                               class="nav-link {% if request.resolver_match.url_name == "panel_create" %}active{% endif %}">
                                <i class="fa fa-edit nav-icon"></i>
                                <p>افزودن ویدیو</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{% url "account:profile" user.pk %}"
                       class="nav-link {% if request.resolver_match.url_name == "profile" %}active{% endif %}">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            پروفایل
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url "account:author" user.pk %}"
                       class="nav-link {% if request.resolver_match.url_name == "author" %}active{% endif %}">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            درخواست معلم شدن
                        </p>
                    </a>
                </li>
                {% if user.is_admin %}
                    <li class="nav-item">
                        <a href="{% url "account:notifications" %}"
                           class="nav-link {% if request.resolver_match.url_name == "notifications" %}active{% endif %}">
                            <i class="nav-icon fas fa-table"></i>
                            <p>
                                اطلاع رسانی
                            </p>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>