TIp_Hub_Net/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('account/', include("account.urls")),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('register/login/', views.Register_Login_View.as_view(), name="register_login"),
    path('otpcode/', views.CzechOtpView.as_view(), name="check_otp"),
    path('panel/', views.PanelUser.as_view(), name="panel_user"),
    path('panelcreate/', views.PanelCreateUser.as_view(), name="panel_create"),
    path('panelupdate/<int:pk>', views.PanelUpdateUser.as_view(), name="panel_update"),
    path('profile/user/<int:pk>', views.ProfileUser.as_view(), name="profile"),
    path('author/about/<int:pk>', views.author_about.as_view(), name="author"),
    path('notification/', views.NotificationView.as_view(), name="notifications"),
    path('notification/update/<int:pk>', views.NotificationUpdate.as_view(), name="notifications_update"),
    path('notification/create/<int:pk>', views.NotificationCreate.as_view(), name="notifications_create"),
    path('logout/', views.user_logout, name='logout'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path('<int:pk>/<slug:slug>/', views.VideoDetail, name='detail'),
    path('<int:pk>/<slug:slug>/', views.HitCount.as_view(), name='detail'),
    path('videolist/', views.VideoList, name='video_all'),
    path('category/<int:pk>/', views.Category_Detail, name='category'),
    path('search/', views.Search, name='search'),
    path('like/<int:pk>/<int:id>/', views.likeDetail, name='like'),
    path('notification/<int:pk>', views.NotificationView.as_view(), name='notification'),
]

templates/includes/footer.html
{% load static %}

<!-- footer -->
<footer>
    <div class="container-fluid py-5">

        <section class="row d-flex align-items-baseline footer-items">
            <div class="col-6 col-sm-6 col-md-3 col-lg-3">
                <div>
                    <h6 class="mb-3 text-white"><span class="border-bottom">خدمات مشترکین</span></h6>
                    <a href="">
                        <p>راهنمای استفاده</p>
                    </a>
                    <a href="">
                        <p>سوالات متداول </p>
                    </a>
                    <a href="">
                        <p>قوانین و مقررات </p>
                    </a>
                    <a href="">
                        <p>پیشنهاد آموزش </p>
                    </a>
                </div>
            </div>
            <div class="col-6 col-sm-6 col-md-3 col-lg-3">
                <div>
                    <h6 class="mb-3 text-white"><span class="border-bottom">خدمات مشترکین</span></h6>
                    <a href="">
                        <p>راهنمای استفاده</p>
                    </a>
                    <a href="">
                        <p>سوالات متداول </p>
                    </a>
                    <a href="">
                        <p>قوانین و مقررات </p>
                    </a>
                    <a href="">
                        <p>پیشنهاد آموزش </p>
                    </a>
                </div>
            </div>
            <div class="col-6 col-sm-6 col-md-3 col-lg-3">
                <div>
                    <h6 class="mb-3 text-white"><span class="border-bottom">خدمات مشترکین</span></h6>
                    <a href="">
                        <p>مستندات جنگو</p>
                    </a>
                    <a href="">
                        <p>آموزش دارت</p>
                    </a>
                    <a href="">
                        <p>خلاصه کتاب‌های پایتون</p>
                    </a>
                    <a href="">
                        <p>چند نکته ی پایتونی</p>
                    </a>
                </div>
            </div>
            <div class="col-6 col-sm-6 col-md-3 col-lg-3">
                <div>
                    <h6 class="mb-3 text-white"><span class="border-bottom">خدمات مشترکین</span></h6>
                    <a href="" class="">
                        <img src="#" alt="">
                        خراسان رضوی، خیابان نادری، خیابان امیری، کوچه مهرگان، پلاک ۱۴، کد پستی 6381838168
                    </a>
                    <a href="" class="">
                        <img src="#" alt="">
                        پشتیبانی: 09123456789
                    </a>
                    <a href="" class="">
                        <img src="#" alt="">
                        30009010
                    </a>
                    <a href="" class="">
                        <img src="#" alt="">
                        email.fake@gmail.com
                    </a>

{#                    <button class="footer-btn my-3">ارسال پیام</button>#}
{##}
{#                    <div class="social-media d-flex align-items-center flex-wrap ">#}
{#                        <a href=""> <i class="fa fa-instagram"></i></a>#}
{#                        <a href=""> <i class="fa fa-telegram"></i></a>#}
{#                        <a href=""> <i class="fa fa-whatsapp"></i></a>#}
{#                        <a href=""> <i class="fa fa-twitter"></i></a>#}
{#                    </div>#}

                </div>
            </div>
        </section>

    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="{% static "components/bootstrap/bootstrap.bundle.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>

<script src="{% static "components/owl-carousel/owl.carousel.min.js" %}"></script>
<script src="{% static "js/script.js" %}"></script>

templates/includes/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "components/bootstrap/bootstrap-rtl.min.css" %}">
    <link rel="stylesheet" href="{% static "components/owl-carousel/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/font-vazir.css" %}">
    <title>آموزش برنامه نویسی</title>
</head>

templates/includes/header.html
{% load static %}
<!-- top-header -->
<div class="shadow position-fixed w-100 h-100 d-md-none d-lg-none"></div>
<!-- top-header -->
<header class="position-relative">
    {# Mobile  #}
    <section
            class="nav-header-box-mob d-flex d-sm-flex d-md-none  align-items-center justify-content-between d-md-none d-lg-none position-fixed">
        <div class="hamburger-icon">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </div>
        <div class="logo">
            <a href="{% url "home:home" %}"><img src="{% static "image/logo2.png" %}" class="logo-img img-fluid"
                                                 alt=""/></a>
        </div>

        <div class="d-flex align-items-center">
            <div class="header-account">
                <div class="notification-box dropdown">
                    {% if request.user.is_authenticated %}
                        <a href="#" class="btn login-btn" type="button" id="dropdownMenuButton"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if request.user.image %}
                                <img src="{{ request.user.image.url }}" alt="">
                            {% else %}
                                <img src="{% static "image/sutdent-prof.png" %}" alt="">
                            {% endif %}
                        </a>

                        <div class="dropdown-menu account-menu-items custom-bg"
                             aria-labelledby="dropdownMenuButton">
                            <a href="{% url "account:panel_user" %}">پنل کاربری</a>
                            <a href="{% url "account:logout" %}"> خروج</a>
                        </div>

                    {% else %}

                        <a href="" class="btn account-btn" type="button"
                           id="dropdownMenuButton"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="prepend-icon ml-1">
                                    <i class="fa fa-user-circle"></i>
                                </span> <span>حساب کاربری </span>
                        </a>

                        <div class="dropdown-menu account-menu-items custom-bg"
                             aria-labelledby="dropdownMenuButton">
                            <a class="" href="{% url "account:register_login" %}">ثبت نام/ورود</a>
                        </div>

                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    {# Mobile  #}

    {#  Desktop  #}
    <div class="main-header position-relative">

        <div class="nav-header-box mob1 d-md-flex d-lg-flex align-items-center justify-content-between">

            <div class="d-flex flex-column flex-md-row align-items-center pr-md-4">
                <div class="logo d-flex justify-content-center align-items-center ml-3">
                    <a href="{% url "home:home" %}"><img src="{% static 'image/logo2.png' %}"
                                                         class="logo-img img-fluid"/></a>
                </div>
                <!-- SEARCH -->
                <form action="{% url "home:search" %}" method="GET" class="nav-search-btn">
                    <input name="q" type="text" placeholder="جستجو">
                    <button type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
                <!-- END SEARCH -->

            </div>
            <div class="d-block d-md-flex align-items-center pl-md-4">
                <!-- NOTIFICATIONS -->
                {% if request.user.is_authenticated %}
                    <div class="dropdown notification-box">
                        <div class="position-relative d-none d-md-block " type="button" id="dropdownMenuButton"
                             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{% static 'image/notification.png' %}" class="notification-img" alt="">
                            <div class="badge">{{ request.user.notification.all.count }}</div>
                        </div>
                        {% if request.user.notification.all %}
                            <div class="dropdown-menu notification-menu-items custom-bg"
                                 aria-labelledby="dropdownMenuButton">
                                {% for notification in request.user.notification.all|slice:":5" %}
                                    <a class="border-bottom"
                                       href="{{ notification.get_absulot_url }}"> {{ notification.body|safe }}<strong>({{ notification.sender.status }})</strong></a>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
                <!-- END NOTIFICATIONS -->

                <div class="header-account d-none d-md-block">
                    <div class="notification-box dropdown">
                        {% if request.user.is_authenticated %}
                            <a href="#" class="btn login-btn" type="button" id="dropdownMenuButton"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if request.user.image %}
                                    <img src="{{ request.user.image.url }}" alt="image">
                                {% else %}
                                    <img src="{% static "image/sutdent-prof.png" %}" alt="image">
                                {% endif %}
                            </a>

                            <div class="dropdown-menu account-menu-items custom-bg"
                                 aria-labelledby="dropdownMenuButton">
                                <a href="{% url "account:panel_user" %}">پنل کاربری</a>
                                <a href="{% url "account:logout" %}"> خروج</a>
                            </div>

                        {% else %}

                            <a href="" class="btn account-btn" type="button"
                               id="dropdownMenuButton"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="prepend-icon ml-1">
                                    <i class="fa fa-user-circle"></i>
                                </span> <span>حساب کاربری </span>
                            </a>

                            <div class="dropdown-menu account-menu-items custom-bg"
                                 aria-labelledby="dropdownMenuButton">
                                <a href="{% url "account:register_login" %}">ثبت نام/ورود</a>
                            </div>

                        {% endif %}
                    </div>
                </div>
            </div>
            {#  navbar  #}
            <nav class="nav-menu p-0 m-0 d-flex d-sm-flex d-md-none d-lg-none">
                {% for cat in categories %}
                    <li id="" class="mx-3">
                        <a class="nav-menu-item-mob" href="{% url 'home:category' cat.id %}">{{ cat.title }}</a>
                    </li>
                {% endfor %}
            </nav>
            {#  navbar  #}
        </div>
    </div>
    {#  Desktop  #}

    {#  navbar  #}
    <nav class="nav-menu nav-menu-pc  d-none d-md-flex px-4" id="navbar">
        {% for cat in categories %}
            <li id="li-" class="mx-3 menu-item">
                <a href="{% url 'home:category' cat.id %}" class="nav-menu-item">
                    {{ cat.title }}
                </a>
            </li>
        {% endfor %}
    </nav>
    {#  navbar  #}
</header>